### ISSUE TITLE
create a file hasher using python with different hashing methods.

### ISSUE THREAD

**Issue by tejan-singh** [sanscript-tech/hacking-tools-scripts#12] opened 2020-10-18 09:19 UTC
it should include hashes like md5, sha etc
hint: you can use hashlib.

**Comment by harshareddy794** [comment] 2020-10-18 09:21
@tejan-singh  Can I work on this issue?

**Comment by tejan-singh** [comment] 2020-10-18 09:22
yes you can work on this.

**Comment by harshareddy794** [comment] 2020-10-19 06:40
My PR got merged but the issue is still open can you check @tejan-singh

**Closed as completed** 2020-10-20 09:58 UTC
Labels: AOS2020, Medium Level, Assigned
